name: Print hello world

on:
  push:
    branches:
      - main
      
jobs:
  example:
    runs-on: ubuntu-latest 
    
    steps:
    - name: example steps
      run: echo "hello v2"
    - name: checkout code
      uses: actions/checkout@v4.2.2
    - name: list repository files
      run: ls -la
    
